---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Remove old versions of docker packages
  apt: name=={{ item }} state=absent update_cache=yes force_apt_get=yes
  loop: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes force_apt_get=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name={{ item }} state=latest
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']


- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Adding user jenkins to docker 
  user: name=jenkins
        group=docker
        shell=/bin/bash
        append=yes

- name: Change ownership of /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    mode: 0777
    
# Creates the number of containers defined by the variable create_containers, using values from vars file
- name: Create default containers
  docker_container:
    name: train_sonarqube
    image: sonarqube:7.9.5-community 
    state: present
    ports:
     - "9000:9000"
